Fix ruination mode crash: add ruination_mode to FigaroCastleWOR.MAP_SHUFFLE
Similar to the VeldtCaveWOR fix, FigaroCastleWOR.MAP_SHUFFLE didn't
include args.ruination_mode. This meant map_shuffle_mod() was never
called in ruination mode, and AddSwitchyardEvent(1507, ...) was never
executed.

Later, maps.write() tries to update event_exit_info[1507] by looking
up the switchyard tile coordinates via switchyard_xy(1507), but the
tile doesn't exist because it was never created.

Error: IndexError: get_event: could not find event at 6 1